repos:
  - repo: local
    hooks:
    - id: format
      name: format
      entry: uv run ruff format .
      language: system
      types: [python]

    - id: lint
      name: lint
      entry: uv run ruff check --fix .
      language: system
      types: [python]

    # - id: mypy
    #   name: mypy
    #   entry: poetry run mypy .
    #   language: system
    #   types: [python]
